### PR TITLE
Fix recursive argument in drive_ls

### LINKED ISSUE #265: drive_ls "recursive" flag broken
> drive_ls(..., recursive = T)

Only expands the first "folder" in the path.

### PR DESCRIPTION
**Pull request by Falnesio**
Fixes #265, the problem related to the use of the recursive argument in drive_ls for shared drives.

### CODE REVIEW

**Comment by Falnesio** [comment]
Sharing working example from before fix and after fix

**Before fix:**
```r
## install googledrive from this PR
## install_github("tidyverse/googledrive#190")
library(googledrive)

## I have many tokens and want to use a specific one.
## Other people can just let the OAuth2 flow happen.
drive_auth("tidyverse-noncaching-token.rds")

drive_ls(as_id("1QPDu46aGHh8EjdJm-i12NzcVVBlVjyvt"), recursive = TRUE, type="folder")
# A dribble: 3 x 3
#  name  id                                drive_resource   
#  <chr> <drv_id>                          <list>           
#1 C     1iuIBsZTQNQPfdYkFqRdsbHX8fcpjb3ya <named list [32]>
#2 A     17qBnOnqjP3nemZdo5bcY4htnp4IZJrxg <named list [32]>
#3 B     186JZdflymqlq-DVa8S0jXbMGhcTEF5Vv <named list [32]>

```
**After fix:**
```r
## install googledrive from this PR
## install_github("tidyverse/googledrive#190")
library(googledrive)

## I have many tokens and want to use a specific one.
## Other people can just let the OAuth2 flow happen.
drive_auth("tidyverse-noncaching-token.rds")

drive_ls(as_id("1QPDu46aGHh8EjdJm-i12NzcVVBlVjyvt"), recursive = TRUE, type="folder")
# A dribble: 6 x 3
#  name  id                                drive_resource   
#  <chr> <drv_id>                          <list>           
#1 B.3   1N9BRc3DNfBNa3csrbe8vnmBTO0f8IOSa <named list [32]>
#2 C     1iuIBsZTQNQPfdYkFqRdsbHX8fcpjb3ya <named list [32]>
#3 B.2   1Q0o-D6r8xJgIOkyqkrGCLk5vGOdR-Rkg <named list [32]>
#4 A     17qBnOnqjP3nemZdo5bcY4htnp4IZJrxg <named list [32]>
#5 A.1   1Qy6-CS5KAbYTuvu4jZjj7rL90j9kdg1O <named list [32]>
#6 B     186JZdflymqlq-DVa8S0jXbMGhcTEF5Vv <named list [32]>
```

**Comment by Falnesio** [comment]
Some things to note about `drive_ls()` in itself when relating to shared drives:

1. You need to have access to the shared drive for the `drive_ls()` function to not output an error.
2. Having top level viewer access to the shared drive will make `drive_ls()` output a blank tibble. All other access works fine.
```r
drive_ls(as_id("1QPDu46aGHh8EjdJm-i12NzcVVBlVjyvt"), recursive = TRUE, type="folder")
## A dribble: 3 x 3
#  name  id                                drive_resource   
#  <chr> <drv_id>                          <list>           
#1 A     17qBnOnqjP3nemZdo5bcY4htnp4IZJrxg <named list [30]>
#2 B     186JZdflymqlq-DVa8S0jXbMGhcTEF5Vv <named list [30]>
#3 C     1iuIBsZTQNQPfdYkFqRdsbHX8fcpjb3ya <named list [30]>
```

**Comment by Falnesio** [comment]
@jennybc What gmail address may I associate to the shared drive so that my examples work for you?

**Comment by jennybc** [comment]
I'll have to come back to this later, but I have access to shared drives. So if there were setup code (like, make a folder, put a new doc in it), I should be able to replicate any example.

**Comment by jennybc** [comment]
I changed the solution, to eliminate an extra `drive_get()` call for each sub-folder. We already have the ID of the shared drive, if relevant, so we just need to pass that info along.

Thanks for such a clear example and a working solution -- that was very helpful!

**Pull request merged**
