### PR TITLE
Recursive drive path helper; relates to #7 and #24

### PR DESCRIPTION
**Pull request by jennybc**
#7 Interface of drive_list()
#24 Path handling toolkit

This is still WIP, so not quite done.

@LucyMcGowan Do you want to have a look around and discuss? I'm especially interested to know if you see anything where you feel this is a step *backwards*.

I still need to add more tests but the whole testing setup is very frustrating right now, so am also holding off a bit. I think we need to create some directory structures that are "stable", so our tests are faster. If we aren't testing a function that edits Drive, the test should not edit Drive. We should have the  content ready and waiting to test against.

### CODE REVIEW

**Comment by LucyMcGowan** [comment]
I agree re:testing - I was originally trying to set it up so someone who didn't have access to our testing account could run everything on their own account, but it seems very superfluous to recreate these folders everytime. Maybe I should write up a script that creates them all *one time* & have it commented out in the test folder like we have other file generating scripts?

**Comment by LucyMcGowan** [comment]
Also, I ended up changing the tests in the mime type PR so that it created unique folders so they won't fail for those reasons, so I'll set up the general structure that way as well.

**Comment by LucyMcGowan** [comment]
just took it for a quick spin & it looks great! I'm going to revamp tests a bit today to be less of a huge pain (but maybe we can make a robust plan on Wednesday)

**Comment by jennybc** [comment]
I'm trying to rescue the appveyor build. I think I'll merge, so it's doesn't get too large and we don't have too many things evolving separately. About to look at your mime table PR again.

**Pull request merged**
