### PR TITLE
Vectorize drive_get() and rationalize drive_path*(); closes to #76

### PR DESCRIPTION
**Pull request by jennybc**
I see no reason why `drive_get()` should not be vectorized. When n things go in, n things come out (we still need to think about bad ids #75).

The functions that take path as input are trickier: there's the issue of whether the input is allowed to have length > 1 (which I have straightened out here) and whether the output is allowed to have length > 1 (which is a job for whatever `is_one()` becomes #77).

I still want to add some tests, but overall @LucyMcGowan do you see any problem with this? Also, can you think of downstream adjustments we can or need to make?

### CODE REVIEW

**Comment by LucyMcGowan** [comment]
I think this looks 👍 - the only thing I think is a bit tricky is figuring out how to tell someone if *some* of the ids are bad (or maybe it's all or nothing - if one is bad it stops regardless?)

**Comment by jennybc** [comment]
Let's leave the "bad ids" problem in #75. Not sure if it should error or those rows should be non-existent or filled with NAs.

I think there are downstream implications here:

  * Anything that was counting on `drive_path()` to make sure there was only 1 input needs to switch to `is_one()`.
  * Anything that could benefit from vectorization, such as `drive_delete()`, should do it internally now.

**Comment by LucyMcGowan** [comment]
are you working on those 👆, or should I take a stab at them?

**Comment by jennybc** [comment]
I propose you tackle the second (search for functions that can clearly be vectorized but aren't) and I'll work on the first.

I think you will find many functions that *could* be vectorized but perhaps we should not rush into it, such as moving files or modifying publishing/sharing status. Recommend you start with the ones that are no-brainers. It might just be `drive_delete()`? As you encounter ones that require more thought, open an issue.

**Comment by LucyMcGowan** [comment]
I think the obvious ones are `drive_delete()`, `drive_share_link()`, and `drive_is_published()` - I believe each of those can currently handle `dribble`s with multiple rows, so their code wouldn't change with this update since `as_dribble()` would just output an n-rowed `dribble` versus a 1 row dribble.

**Comment by LucyMcGowan** [comment]
😱 `as_dribble.NULL` is brilliant!

**Pull request merged**
